services:
  - type: web
    name: battleship
    env: node
    buildCommand: npm install
    startCommand: node ./bin/www
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: battleship-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: battleship-db
    databaseName: battleship
    user: battleship